CREATE TABLE `hero` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` varchar(64) NOT NULL DEFAULT '' COMMENT 'uid',
  `name` varchar(255) NOT NULL DEFAULT '' COMMENT '名称',
  `gender` int(11) NOT NULL DEFAULT '0' COMMENT '性别',
  `world_level` bigint(20) NOT NULL DEFAULT '1' COMMENT '世界等级',
  `world_occupation` int(11) NOT NULL DEFAULT '0' COMMENT '世界职业',
  `world_race` int(11) NOT NULL DEFAULT '0' COMMENT '世界种族',
  `experience_point` bigint(20) NOT NULL DEFAULT '1' COMMENT '经验值',
  `health_point` bigint(20) NOT NULL DEFAULT '1' COMMENT '生命值',
  `magic_point` bigint(20) NOT NULL DEFAULT '1' COMMENT '魔法值',
  `physical_attack` bigint(20) NOT NULL DEFAULT '1' COMMENT '物理攻击',
  `magic_attack` bigint(20) NOT NULL DEFAULT '1' COMMENT '魔法攻击',
  `physical_defense` bigint(20) NOT NULL DEFAULT '1' COMMENT '物理防御',
  `magic_defense` bigint(20) NOT NULL DEFAULT '1' COMMENT '魔法防御',
  `physical_hit` bigint(20) NOT NULL DEFAULT '1' COMMENT '物理命中',
  `magic_hit` bigint(20) NOT NULL DEFAULT '1' COMMENT '魔法命中',
  `physical_dodge` bigint(20) NOT NULL DEFAULT '1' COMMENT '物理闪避',
  `magic_dodge` bigint(20) NOT NULL DEFAULT '1' COMMENT '魔法闪避',
  `base_strength` bigint(20) NOT NULL DEFAULT '1' COMMENT '力量',
  `base_agility` bigint(20) NOT NULL DEFAULT '1' COMMENT '敏捷',
  `base_intelligence` bigint(20) NOT NULL DEFAULT '1' COMMENT '智力',
  `create_date` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_date` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COMMENT = '基础信息表';